Expand supported version range for Node.js
The main motivation is this: a library maintainer wanting to support and
ancient version of Node.js should not be discouraged from using this
library (for their users on modern Node.js versions) as a result of it
not being compatible with those older Node.js versions. In general,
support for Node.js versions prior to the introduction of the linear
engine _should_ be trivial because this library should be a noop.

This pushes the lower bound down to Node.js v9.0.0, expanding on the
suppoorted ranges for Node.js 12 and 14, and adding support for Node.js
13.

Tested locally with:

    $ npx nve '9.0.0,10.0.0,11.0.0,12.0.0,
    13.0.0,14.0.0,15.0.0,16.0.0,17.0.0,
    18.0.0,19.0.0,20.0.0,21.0.0,22.0.0,
    23.0.0,24.0.0,25.0.0,26.0.0' node node_test.cjs

Stopped there because on 8.0.0 we get an error that is less simple to
fix, namely

    $ npx nve 8.0.0 node node_test.cjs
    Error: Cannot find module 'perf_hooks'
    [...]